# Generated by Django 5.2.10 on 2026-02-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('harmful', 'Harmful Content'), ('sensitive', 'Sensitive Topic'), ('off_topic', 'Off Topic')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_flags', to='conversation.message')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('safety', 'Safety Concern'), ('mood', 'Mood Change'), ('milestone', 'Milestone'), ('session', 'Session Summary')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='authentication.parentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='conversation.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='content_saf_session_f4257c_idx'), models.Index(fields=['parent'], name='content_saf_parent__20f7ff_idx')],
            },
        ),
    ]
