"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from datetime import timedelta

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(key: str, default: bool = False) -> bool:
    v = os.getenv(key)
    if v is None:
        return default
    return v.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(key: str, default: str = '') -> list:
    """Comma-separated env var -> list. Strips spaces and drops empty items."""
    return [item.strip() for item in os.getenv(key, default).split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DEBUG = os.getenv('DEBUG', '0') == '1'

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set in production (DEBUG=False).'
        )

# Production: set DJANGO_ALLOWED_HOSTS=alsadiqai.com (comma-separated for several).
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,backend')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'authentication',
    'conversation',
    'session_moral_context',
    'content_safety',
    'reporting',
    'gamification',
    'superadmin',
    'demo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'authentication.middleware.UpdateChildLastSeenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'alsadiq_db'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.getenv('POSTGRES_HOST', 'db'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Cache: LocMem only for this phase (no Redis required). Swap to RedisCache when scaling.
# https://docs.djangoproject.com/en/6.0/topics/cache/

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'alsadiq-locmem',
    }
}

# "guards" cache: counts for the demo throttles (conversation/throttles.py). It must be shared
# by all gunicorn workers, so it is Redis whenever Redis is configured (REDIS_URL, or
# REDIS_HOST + REDIS_PORT as in .env.example). Without Redis (tests, a bare dev run) it falls
# back to the per-process LocMem cache.
_GUARDS_REDIS_URL = os.getenv('REDIS_URL') or (
    f"redis://{os.getenv('REDIS_HOST')}:{os.getenv('REDIS_PORT', '6379')}/{os.getenv('REDIS_GUARDS_DB', '0')}"
    if os.getenv('REDIS_HOST') else ''
)
if _GUARDS_REDIS_URL:
    CACHES['guards'] = {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': _GUARDS_REDIS_URL,
        'KEY_PREFIX': 'throttle',
        'OPTIONS': {'socket_timeout': 1, 'socket_connect_timeout': 1},
    }
else:
    CACHES['guards'] = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'alsadiq-guards-locmem',
    }

# "throttle" cache: the DRF rate-limit counters (config/throttling.py). Same Redis as the guards
# (REDIS_URL, or REDIS_HOST + REDIS_PORT), another key prefix. LocMem without Redis (tests, dev).
# Short timeouts: on a Redis error the throttles fall back to a per-process LocMem counter; this bounds the delay.
if _GUARDS_REDIS_URL:
    CACHES['throttle'] = {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': _GUARDS_REDIS_URL,
        'KEY_PREFIX': 'drf',
        'OPTIONS': {'socket_timeout': 0.5, 'socket_connect_timeout': 0.5},
    }
else:
    CACHES['throttle'] = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'alsadiq-throttle-locmem',
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'authentication.validators.StrongPasswordValidator',
    },
]

# REST Framework Configuration

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # simplejwt's JWTAuthentication, plus: a shared demo account's token
        # stops working the moment its lease ends (see demo/authentication.py).
        'demo.authentication.DemoLeaseJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'config.throttling.SharedAnonRateThrottle',
        'config.throttling.SharedUserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        # Was effectively ~180/min (per-worker LocMem x ~3 workers); now one shared counter.
        'user': '180/minute',
        'auth': os.getenv('AUTH_RATE') or '5/minute',
        'registration': '3/minute',
        'password_reset': '3/minute',
        # Per target email (hashed), across all IPs: stops a mail-bomb of one parent.
        'password_reset_email': '3/hour',
        # A reset link is an HMAC token; this only caps guessing, per IP.
        'password_reset_confirm': '5/minute',
        # Refresh was under the shared anon bucket; same 30/min, now its own bucket (per IP).
        'token_refresh': '30/minute',
        # A signed-in child changing their own password, per user.
        'password_change': '5/hour',
        # Each session start creates a LiveKit room (costs money). Always on, per user, next
        # to the demo-only SessionStartThrottle. A reload starts a new session, so keep headroom.
        'session_start_user': os.getenv('SESSION_START_USER_RATE') or '30/hour',
        # One-click demo (only active when DEMO_MODE=1).
        # demo_start is per client IP (anonymous); demo_reset is a signed-in call, so
        # DRF counts it per demo user. Judges sit behind one office NAT, so the old 10/hour
        # locked a whole room out (and the busy page's own retries count too).
        # 120/hour still stops one script from cycling through the pool all day.
        'demo_start': os.getenv('DEMO_START_RATE') or '120/hour',
        'demo_reset': os.getenv('DEMO_RESET_RATE') or '120/hour',
    },
    # Throttles key on the client IP. Behind the single Caddy hop in production set
    # DRF_NUM_PROXIES=1 so only the address Caddy appended to X-Forwarded-For counts, never
    # one the client sent. Unset (dev, no proxy) = DRF's default.
    # Unset/blank -> None; an explicit "0" stays 0 (no proxy trusted).
    'NUM_PROXIES': int(_proxies) if (_proxies := os.getenv('DRF_NUM_PROXIES', '').strip()) else None,
}

# JWT Configuration

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    # Same as simplejwt's, but refuses demo tokens whose lease has ended.
    'TOKEN_REFRESH_SERIALIZER': 'demo.serializers.DemoLeaseTokenRefreshSerializer',
}

# CORS Configuration

# Production: set CORS_ALLOWED_ORIGINS=https://alsadiqai.com (comma-separated for several).
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS', 'http://localhost:5173')
# The child screen reads Retry-After on a 429 to count down honestly.
CORS_EXPOSE_HEADERS = ['Retry-After']

# Default PK type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
AUTH_USER_MODEL = 'authentication.User'

# ============================================
# Email Configuration
# ============================================
# Dev default: console backend (prints emails to terminal).
# Production: set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend in .env
# and configure SMTP credentials (Gmail, SendGrid, etc.).

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', '1') == '1'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Al-Sadiq Al-Sadouq <noreply@alsadiq.dev>')

# Password reset token expiry (seconds). Default: 1 hour.
PASSWORD_RESET_TIMEOUT = int(os.getenv('PASSWORD_RESET_TIMEOUT', '3600'))

# Frontend URL used to construct password-reset links in emails.
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# ============================================
# LiveKit
# ============================================

LIVEKIT_API_KEY = os.getenv('LIVEKIT_API_KEY', 'APIKeyDevKey')
# Must match LiveKit server key secret (min 32 chars in livekit.yaml for current server builds)
_DEV_LIVEKIT_API_SECRET = 'dev_livekit_api_secret_minimum_32_chars_x'
LIVEKIT_API_SECRET = os.getenv('LIVEKIT_API_SECRET', _DEV_LIVEKIT_API_SECRET)
if not DEBUG and LIVEKIT_API_SECRET in ('', _DEV_LIVEKIT_API_SECRET):
    # The dev secret is public in this repo: anyone could mint room tokens and sign webhooks.
    raise ImproperlyConfigured(
        'LIVEKIT_API_SECRET must be set to a real secret in production (DEBUG=False).'
    )
# WebSocket URL for server-side / agents (e.g. ws://livekit:7880 inside Docker)
LIVEKIT_URL = os.getenv('LIVEKIT_URL', 'ws://localhost:7880')
# URL returned to browsers in session API — must be reachable from the user's machine (not Docker service names)
LIVEKIT_PUBLIC_URL = os.getenv('LIVEKIT_PUBLIC_URL', LIVEKIT_URL)


# ============================================
# One-click demo ("Try Al-Sadiq") - OFF unless DEMO_MODE=1
# ============================================
# A pool of synthetic families is leased to visitors by POST /api/demo/start.
# See backend/demo/ and docs/hackathon/DEMO-LOGIN.md.

DEMO_MODE = _env_bool('DEMO_MODE', False)
# How many seeded families exist (seed_demo creates this many; at most the
# families listed in demo/content.py, which is 40).
# Sized for a judging day: about 30 judges, some on a phone and a laptop at once.
DEMO_POOL_SIZE = int(os.getenv('DEMO_POOL_SIZE', '40'))
# How long a visitor keeps a family before it can be leased again (seconds).
# Kept at 45 minutes: the landing page and the submission docs promise "45 minutes".
# With 40 families that is 53 new visitors an hour at the busiest. Lower it with the
# env var (and the landing copy) if a single browser per judge is not enough.
DEMO_LEASE_SECONDS = int(os.getenv('DEMO_LEASE_SECONDS', '2700'))

if DEMO_MODE and os.getenv('REDIS_HOST'):
    # The lease lock and the throttles must be shared between gunicorn workers,
    # so use Redis for the cache. Default stays LocMem when demo mode is off.
    # Only the default alias is replaced: the "guards" cache defined above must survive
    # (rebinding CACHES here dropped it, and every session start then failed in demo mode).
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://{host}:{port}/1'.format(
            host=os.getenv('REDIS_HOST'),
            port=os.getenv('REDIS_PORT', '6379'),
        ),
    }


# ============================================
# Reporting pipeline (post-session LLM)
# ============================================

REPORTING_GENERATE_QUESTS = _env_bool('REPORTING_GENERATE_QUESTS', True)
# The quest LLM sees the child's open-quest board and decides "add" or "skip"
# itself. The settings below are mechanical backstops, not the primary gate.
#
# Hard backstop: skip the LLM call entirely when the child already has this
# many open (non-completed) AI quests. 0 disables the backstop.
REPORTING_QUESTS_MAX_OPEN = int(os.getenv('REPORTING_QUESTS_MAX_OPEN', '5'))
# Legacy opt-in throttle: at most one AI quest batch per child per local day.
# Off by default — the LLM's decision step replaces it.
REPORTING_QUESTS_DAILY_CAP = _env_bool('REPORTING_QUESTS_DAILY_CAP', False)
# Legacy opt-in throttle: skip quest LLM when child has >= MAX_PENDING incomplete AI quests.
REPORTING_QUESTS_SKIP_IF_PENDING = _env_bool('REPORTING_QUESTS_SKIP_IF_PENDING', False)
REPORTING_QUESTS_MAX_PENDING = int(os.getenv('REPORTING_QUESTS_MAX_PENDING', '1'))
# How many recently completed quests to show the LLM (novelty/dedup hints).
REPORTING_QUESTS_RECENT_LIMIT = int(os.getenv('REPORTING_QUESTS_RECENT_LIMIT', '10'))

# Generate/update a parent-facing WeeklySummary after each session via LLM.
REPORTING_GENERATE_WEEKLY_SUMMARY = _env_bool('REPORTING_GENERATE_WEEKLY_SUMMARY', True)
# Skip weekly summary LLM call if the row for the current week was updated within this many hours.
# Set to 0 to disable throttling (regenerate on every session).
REPORTING_WEEKLY_SUMMARY_THROTTLE_HOURS = int(os.getenv('REPORTING_WEEKLY_SUMMARY_THROTTLE_HOURS', '24'))


# ============================================
# Logging
# ============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'authentication': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'conversation': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Production security settings — only active when DEBUG=0
if not DEBUG:
    # Production: set CSRF_TRUSTED_ORIGINS=https://alsadiqai.com (comma-separated for several).
    CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS')
    # Caddy terminates TLS, so the redirect is on by default. Only set
    # SECURE_SSL_REDIRECT=0 for a plain-HTTP staging box.
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # No browsable API in production: it renders HTML forms for every endpoint.
    # The web and mobile clients only speak JSON. (OPTIONS metadata is unchanged.)
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = ('rest_framework.renderers.JSONRenderer',)
