/**
 * Copy for the child's voice screen: idle, starting, refusals, the text chat, the voice
 * resting, the session clock and the goodbye. Arabic first, short, warm, for ages 6 to 13.
 * No scripture and no codes (anything Islamic comes only from the content bank, via the agent).
 */

export const VOICE_COPY = {
  ar: {
    dir: 'rtl',
    lang: 'ar',
    // Idle
    idleTitle: 'نتحدّث مع الصديق؟',
    idleBody: 'ابدأ الحديث، وسنتعلّم ونلعب معًا.',
    start: 'ابدأ الحديث',
    langToggle: 'English',
    langToggleLang: 'en',
    langToggleLabel: 'Switch to English',
    // Starting
    starting: 'نجهّز لك الغرفة…',
    startingSlow: 'يستغرق الأمر وقتًا أطول قليلًا، لحظات ونبدأ…',
    // Session chrome
    endSession: 'إنهاء الحديث',
    toChat: 'الانتقال إلى الكتابة',
    toVoice: 'الانتقال إلى الصوت',
    modeVoice: 'صوت', // avatar-integ: the Voice | Chat pill (WebUI photo 1)
    modeChat: 'كتابة',
    mute: 'كتم الصوت',
    unmute: 'تشغيل الصوت',
    micOn: 'كتم الميكروفون',
    micOff: 'تشغيل الميكروفون',
    // hk-14: the call keys' words, the paused-mic banner and hold-to-talk
    micLabelOn: 'يعمل',
    micLabelPaused: 'متوقّف',
    micLabelHold: 'اضغط مطوّلًا',
    micLabelHeld: 'يسمعك',
    endLabel: 'إنهاء',
    soundLabel: 'الصوت',
    micPausedBanner: 'الميكروفون متوقّف · الصديق لا يسمعك',
    holdToTalk: 'اضغط لتتكلّم',
    holdBanner: 'اضغط مطوّلًا على الميكروفون لتتكلّم',
    level: (n) => `المستوى ${n}`,
    progress: 'التقدّم',
    // Status pill on the avatar stage (avatar-integ)
    statusConnecting: 'جارٍ الاتصال...',
    statusDisconnected: 'انقطع الاتصال',
    statusWaiting: 'ننتظر الصديق...',
    statusSpeaking: 'الصديق يتحدّث',
    statusMicOff: 'الميكروفون مغلق',
    statusListening: 'الصديق يسمعك',
    // Exit dialog
    exitTitle: 'ننهي الحديث؟',
    exitBody: 'سنحفظ حديثك مع الصديق.',
    exitYes: 'نعم، أنهِ الحديث',
    exitNo: 'لا، أكمل',
    // Lost connection
    dropped: 'يبدو أن الاتصال انقطع. جرّب حديثًا جديدًا!',
    newSession: 'محادثة جديدة',
    connectError: 'تعذّر الاتصال. تأكّد من الإنترنت ثم حاول مرة أخرى.',
    genericError: 'حدث خطأ أثناء البدء. حاول مرة أخرى.',
    errorTitle: 'لم نتمكّن من البدء',
    tryAgain: 'حاول مرة أخرى',
    // Text chat
    chatPlaceholder: 'اكتب شيئًا للصديق…',
    chatSend: 'إرسال',
    chatEmpty: 'اكتب أي شيء، والصديق يجيبك.',
    chatTitle: 'نتحدّث بالكتابة',
    ideasTitle: 'جرّب أن تقول:',
    ideas: [
      'ماذا يعني الصدق؟',
      'كيف أكون صديقًا طيبًا؟',
      'أريد أن أخبرك عن يومي',
    ],
    noticeClose: 'إغلاق الرسالة',
    voiceResting: 'صوت الصديق يستريح الآن، فلنتحدّث كتابةً!',
    // Voice resting (voice_error)
    restTitle: 'صوت الصديق يستريح',
    restBody: 'لا بأس يا صديقي. نكمل حديثنا بالكتابة؟',
    restText: 'نتحدّث بالكتابة',
    restOffBody: 'الصديق يستريح الآن. عُد بعد قليل وسنتحدّث معًا.',
    restBack: 'حسنًا',
    // Refusals
    refusals: {
      daily_limit: {
        title: 'يومٌ جميل!',
        body: 'لقد استمتعنا اليوم كثيرًا يا صديقي! عُد غدًا ونكمل حديثنا.',
        action: 'حسنًا، إلى الغد',
        mood: 'moon',
      },
      rate_limited: {
        title: 'مهلًا يا صديقي',
        body: 'بدأنا محادثات كثيرة في وقت قصير. انتظر قليلًا ثم حاول مرة أخرى.',
        action: 'حاول بعد قليل',
        mood: 'hourglass',
      },
      voice_off: {
        title: 'الصديق يستريح',
        body: 'الصديق يستريح الآن. عُد بعد قليل وسنتحدّث معًا.',
        action: 'حسنًا',
        mood: 'moon',
      },
      busy: {
        title: 'الغرفة مشغولة',
        body: 'لدينا ضيوف كثيرون الآن. حاول بعد لحظات.',
        action: 'حاول مرة أخرى',
        mood: 'hourglass',
      },
    },
    retryIn: (s) => `يمكنك المحاولة بعد ${s} ثانية`,
    // Clock
    clockLabel: 'الوقت المتبقي في الحديث',
    oneMinute: 'بقيت دقيقة واحدة. قل للصديق آخر شيء تحبّ أن تقوله!',
    ending: 'اقتربنا من الوداع',
    // The end
    endTitle: 'مع السلامة يا صديقي!',
    endBody: 'كان حديثنا جميلًا جدًا. أراك قريبًا.',
    endStartOver: 'ابدأ من جديد',
    endAgain: 'محادثة جديدة',
    endHome: 'العودة للرئيسية',
    working: 'لحظة…',
    startOverFailed: 'تعذّر البدء من جديد. حاول مرة أخرى.',
  },
  en: {
    dir: 'ltr',
    lang: 'en',
    idleTitle: 'Shall we talk with Al-Sadiq?',
    idleBody: 'Start chatting, and we will learn and play together.',
    start: 'Start talking',
    langToggle: 'العربية',
    langToggleLang: 'ar',
    langToggleLabel: 'التبديل إلى العربية',
    starting: 'Getting your room ready…',
    startingSlow: 'This is taking a little longer, we are coming…',
    endSession: 'End the chat',
    toChat: 'Switch to typing',
    toVoice: 'Switch to voice',
    modeVoice: 'Voice', // avatar-integ: the Voice | Chat pill (WebUI photo 1)
    modeChat: 'Chat',
    mute: 'Mute the voice',
    unmute: 'Unmute the voice',
    micOn: 'Mute the microphone',
    micOff: 'Unmute the microphone',
    // hk-14: the call keys' words, the paused-mic banner and hold-to-talk
    micLabelOn: 'Mic on',
    micLabelPaused: 'Paused',
    micLabelHold: 'Hold',
    micLabelHeld: 'Listening',
    endLabel: 'End',
    soundLabel: 'Sound',
    micPausedBanner: "Mic paused · Al-Sadiq can't hear you",
    holdToTalk: 'Hold to talk',
    holdBanner: 'Press and hold the mic to talk',
    level: (n) => `Level ${n}`,
    progress: 'progress',
    // Status pill on the avatar stage (avatar-integ)
    statusConnecting: 'Connecting...',
    statusDisconnected: 'Disconnected',
    statusWaiting: 'Waiting for Al-Sadiq...',
    statusSpeaking: 'Al-Sadiq is speaking',
    statusMicOff: 'Mic is off',
    statusListening: 'Listening',
    exitTitle: 'End the chat?',
    exitBody: 'Your chat with Al-Sadiq will be saved.',
    exitYes: 'Yes, end it',
    exitNo: 'No, keep going',
    dropped: 'It looks like the connection dropped. Try a new chat!',
    newSession: 'New chat',
    connectError: 'Could not connect. Check your internet and try again.',
    genericError: 'Something went wrong while starting. Please try again.',
    errorTitle: 'We could not start',
    tryAgain: 'Try again',
    chatPlaceholder: 'Tell Al-Sadiq something…',
    chatSend: 'Send',
    chatEmpty: 'Type anything, and Al-Sadiq will answer.',
    chatTitle: 'Chatting by text',
    ideasTitle: 'Try saying:',
    ideas: [
      'What does honesty mean?',
      'How can I be a kind friend?',
      'I want to tell you about my day',
    ],
    noticeClose: 'Close the message',
    voiceResting: "Al-Sadiq's voice is resting, so let's chat by text!",
    restTitle: "Al-Sadiq's voice is resting",
    restBody: "That's okay, my friend. Shall we chat by text?",
    restText: 'Chat by text',
    restOffBody: 'Al-Sadiq is resting right now. Please come back a little later.',
    restBack: 'Okay',
    refusals: {
      daily_limit: {
        title: 'What a lovely day!',
        body: 'We had lots of fun today, my friend! Come back tomorrow and we will chat again.',
        action: 'Okay, see you tomorrow',
        mood: 'moon',
      },
      rate_limited: {
        title: 'Slow down, my friend',
        body: 'We started lots of chats in a short time. Wait a little and try again.',
        action: 'Try in a moment',
        mood: 'hourglass',
      },
      voice_off: {
        title: 'Al-Sadiq is resting',
        body: 'Al-Sadiq is resting right now. Please come back a little later.',
        action: 'Okay',
        mood: 'moon',
      },
      busy: {
        title: 'The room is busy',
        body: 'We have lots of guests right now. Try again in a moment.',
        action: 'Try again',
        mood: 'hourglass',
      },
    },
    retryIn: (s) => `You can try again in ${s}s`,
    clockLabel: 'Time left in this chat',
    oneMinute: 'One minute left. Tell Al-Sadiq the last thing you want to say!',
    ending: 'We are almost saying goodbye',
    endTitle: 'Goodbye, my friend!',
    endBody: 'I really enjoyed our chat. See you soon.',
    endStartOver: 'Start over',
    endAgain: 'New chat',
    endHome: 'Back to home',
    working: 'One moment…',
    startOverFailed: 'Could not start over. Please try again.',
  },
};

/** The text for a language, Arabic when unknown. */
export const voiceCopy = (lang) => VOICE_COPY[lang === 'en' ? 'en' : 'ar'];
