# Generated by Django 5.2.10 on 2026-02-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoralTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IslamicReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('hadith', 'Hadith'), ('quran', 'Quran')], max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, help_text='e.g. "Sahih Bukhari", "Surah Al-Baqarah 2:177"', max_length=255)),
            ],
            options={
                'unique_together': {('reference_type', 'text')},
            },
        ),
        migrations.CreateModel(
            name='MoralContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_source', models.CharField(blank=True, max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moral_contexts', to='conversation.message')),
                ('references', models.ManyToManyField(blank=True, related_name='contexts', to='session_moral_context.islamicreference')),
                ('themes', models.ManyToManyField(blank=True, related_name='contexts', to='session_moral_context.moraltheme')),
            ],
        ),
    ]
