# Generated by Django 5.2.10 on 2026-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_moral_context', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='islamicreference',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Only verified references are served to the agent'),
        ),
        migrations.AddField(
            model_name='islamicreference',
            name='themes',
            field=models.ManyToManyField(blank=True, help_text='Moral themes this reference addresses', related_name='references', to='session_moral_context.moraltheme'),
        ),
        migrations.AlterField(
            model_name='islamicreference',
            name='text',
            field=models.TextField(),
        ),
    ]
