# Generated by Django 5.2.10 on 2026-10-04 12:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_session_livekit_room_name_session_status'),
        ('session_moral_context', '0002_extend_islamicreference_themes_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('keywords_ar', models.JSONField(blank=True, default=list)),
                ('keywords_en', models.JSONField(blank=True, default=list)),
                ('child_description_ar', models.TextField(blank=True)),
                ('child_description_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('verse', 'Verse'), ('hadith', 'Hadith'), ('tafsir', 'Tafsir'), ('aqidah', 'Aqidah'), ('fiqh', 'Fiqh'), ('sirah', 'Sirah'), ('faq', 'FAQ'), ('term', 'Term'), ('story', 'Story')], max_length=10)),
                ('arabic_text', models.TextField(blank=True, help_text='Verses: exact Uthmani text from an approved source; never hand-typed')),
                ('english_text', models.TextField(blank=True)),
                ('child_explanation_ar', models.TextField(blank=True)),
                ('child_explanation_en', models.TextField(blank=True)),
                ('age_band', models.CharField(choices=[('all', 'All'), ('6-9', '6-9'), ('10-13', '10-13')], default='all', max_length=5)),
                ('search_text_norm', models.TextField(blank=True, editable=False)),
                ('surah', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(114)])),
                ('ayah', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('book', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('narrator', models.CharField(blank=True, max_length=200)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('grader', models.CharField(blank=True, max_length=100)),
                ('translation_name', models.CharField(blank=True, max_length=200)),
                ('source_site', models.CharField(blank=True, choices=[('quranpedia.net', 'quranpedia.net'), ('qurancomplex.gov.sa', 'qurancomplex.gov.sa'), ('dorar.net', 'dorar.net'), ('shamela.ws', 'shamela.ws'), ('dawa.center', 'dawa.center'), ('islamic-content.com', 'islamic-content.com')], max_length=30)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('seeded', 'Seeded'), ('reviewed', 'Reviewed')], default='unverified', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServedReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('served_at', models.DateTimeField(auto_now_add=True)),
                ('via', models.CharField(choices=[('inject', 'Inject'), ('tool', 'Tool')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='served', to='session_moral_context.contentitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='served_references', to='conversation.session')),
            ],
        ),
        migrations.CreateModel(
            name='ValueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_moral_context.contentitem')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_moral_context.value')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('value', 'item')},
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='items', through='session_moral_context.ValueItem', to='session_moral_context.value'),
        ),
        migrations.AddConstraint(
            model_name='contentitem',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'verse')), fields=('type', 'surah', 'ayah'), name='uniq_verse_surah_ayah'),
        ),
        migrations.AddConstraint(
            model_name='contentitem',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'hadith'), models.Q(('book', ''), _negated=True), models.Q(('number', ''), _negated=True)), fields=('type', 'book', 'number'), name='uniq_hadith_book_number'),
        ),
    ]
