# Generated by Django 5.2.10 on 2026-10-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_moral_context', '0004_migrate_legacy_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='child_explanation_older_ar',
            field=models.TextField(blank=True, help_text='Deeper explanation for ages 10-13'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='child_explanation_older_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='girls_note_ar',
            field=models.TextField(blank=True, help_text='Extra line shown only to girls (e.g. modesty)'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='girls_note_en',
            field=models.TextField(blank=True),
        ),
    ]
