# Generated by Django 5.2.10 on 2026-10-04 22:21

from django.db import migrations, models


def unverify_legacy_references(apps, schema_editor):
    # Plan 7.1: no legacy reference is served until re-sourced.
    apps.get_model('session_moral_context', 'IslamicReference').objects.update(
        is_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ("session_moral_context", "0005_contentitem_older_and_girls_explanations"),
    ]

    operations = [
        migrations.RunPython(unverify_legacy_references, migrations.RunPython.noop),
        migrations.AddField(
            model_name="contentitem",
            name="arabic_text_search",
            field=models.TextField(
                blank=True, help_text="Verses: plain-script text used only for search"
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="content_level",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C")],
                help_text="A/B/C; blank is filled per type by seed_content",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="disagreement_note_ar",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="disagreement_note_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="keywords_ar",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="keywords_en",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="related",
            field=models.ManyToManyField(
                blank=True,
                related_name="cited_by",
                to="session_moral_context.contentitem",
            ),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="text_edition",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="title_ar",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="title_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="translation_source_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="source_site",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quranpedia.net", "quranpedia.net"),
                    ("qurancomplex.gov.sa", "qurancomplex.gov.sa"),
                    ("dorar.net", "dorar.net"),
                    ("shamela.ws", "shamela.ws"),
                    ("dawa.center", "dawa.center"),
                    ("islamic-content.com", "islamic-content.com"),
                    ("hadeethenc.com", "hadeethenc.com"),
                    ("quranenc.com", "quranenc.com"),
                    ("islamenc.com", "islamenc.com"),
                    ("terminologyenc.com", "terminologyenc.com"),
                    ("mp3quran.net", "mp3quran.net"),
                ],
                max_length=30,
            ),
        ),
    ]
