/**
 * Copy for the demo landing page and the in-app demo banner.
 * Arabic first. Plain words, no scripture (sources only ever come from the content bank).
 *
 * Content owner: the six "values" below are plain-language child wording written by the design
 * team. They are not quotes and carry no source. Please review the wording before the public demo.
 */

// U+2011 (non-breaking hyphen) in "Al‑Sadiq": the bubble never splits the name as "Al- / Sadiq".

export const COPY = {
  ar: {
    dir: 'rtl',
    lang: 'ar',
    brand: 'الصديق الصدوق',
    brandShort: 'الصديق',
    toggleLabel: 'Switch to English',
    login: 'تسجيل الدخول',
    headline: 'الصديق الصدوق، صديق يعلّم طفلك ٣٨ قيمة إسلامية من مصادر موثّقة',
    sub: 'رفيق صوتي للأطفال من ٦ إلى ١٣ سنة. وللأهل لوحة هادئة ترى منها الملخصات الأسبوعية والتنبيهات وموضوعات تعينهم على الحديث مع طفلهم.',
    cta: 'جرّب الصديق',
    ctaLoading: 'نجهّز لك غرفة…',
    privacy: 'بيانات تجريبية فقط: عائلة افتراضية، ولا بيانات حقيقية لأي طفل.',
    judgesTitle: 'للحكّام: ثلاث خطوات',
    steps: [
      { title: 'اضغط «جرّب الصديق»', body: 'تدخل مباشرة غرفة طفل افتراضي، بلا حساب، لمدة ٤٥ دقيقة.' },
      { title: 'تحدّث مع الصديق', body: 'بصوتك أو بالكتابة، وسترى كيف يردّ على طفل.' },
      { title: 'اضغط «عرض وليّ الأمر»', body: 'ترى ملخص الأسبوع والتنبيهات لنفس الطفل.' },
    ],
    // The scene
    greetings: {
      morning: 'السلام عليكم! صباح الخير، أنا الصديق.',
      noon: 'السلام عليكم! أنا الصديق.',
      maghrib: 'السلام عليكم! مساء الخير، أنا الصديق.',
      night: 'السلام عليكم! ظهرت النجوم، أنا الصديق.',
    },
    hint: 'اضغط على الصديق لتبدأ الحديث',
    nudge: 'جرّب تضغط على الفانوس!',
    letsTalk: 'هيا نتكلّم!',
    birdHello: 'مرحبًا يا صديقي البلبل!',
    labels: {
      sadiq: 'تحدّث مع الصديق',
      lantern: 'أشعل الفانوس',
      lanternLit: 'نادِ اليراعات',
      book: 'افتح الكتاب',
      bird: 'سلّم على البلبل',
      birdAsleep: 'البلبل نائم',
    },
    values: [
      { name: 'الصدق', text: 'أقول الحقيقة حتى لو كانت صعبة.' },
      { name: 'الأمانة', text: 'أحفظ ما يُعطى لي وأردّه كما هو.' },
      { name: 'الرحمة', text: 'أكون لطيفًا مع الناس والحيوانات.' },
      { name: 'الشكر', text: 'أقول شكرًا وأقدّر ما عندي.' },
      { name: 'برّ الوالدين', text: 'أساعد أمي وأبي وأسمع كلامهما.' },
      { name: 'الصبر', text: 'أنتظر بهدوء ولا أستسلم.' },
    ],
    sleepLetter: 'ز',
    // Time of day pill (the landing preview)
    timeLabel: 'وقت اليوم في الغابة',
    times: { now: 'الآن', morning: 'الصباح', noon: 'الظهر', maghrib: 'المغرب', night: 'الليل' },
    // Sound pill
    soundOn: 'أصوات الغابة: مفتوحة',
    soundOff: 'أصوات الغابة: مغلقة',
    // Problems
    busyTitle: 'الغرف مشغولة الآن',
    retryIn: (s) => `نحاول معك مجددًا بعد ${s} ثانية`,
    retry: 'حاول الآن',
    errorTitle: 'لم نتمكن من البدء',
    showcaseTitle: 'نسخة للمعاينة',
    showcaseNote: 'الدخول التجريبي يحتاج الخادم المباشر. هذه الصفحة للمعاينة فقط.',
    showcaseLink: 'المعاينة',
    foot: 'مشروع تحدّي الذكاء الاصطناعي الإسلامي',
    // Banner
    demoBadge: 'تجربة',
    parentView: 'عرض وليّ الأمر',
    childView: 'عرض الطفل',
    startOver: 'ابدأ من جديد',
    newDemo: 'ابدأ تجربة جديدة',
    ended: 'انتهت مدة التجربة',
    working: 'لحظة…',
    startedOver: 'جاهزة تجربة جديدة',
    bannerAria: 'شريط التجربة',
    bannerHint: 'تجربة بيانات افتراضية',
    // Child idle screen (ChildIdleStage). Level names are the seeded English ones, translated for the demo.
    idle: {
      talk: 'ابدأ الحديث',
      working: 'لحظة…',
      hello: (name) => (name ? `أهلًا يا ${name}!` : 'أهلًا يا صديقي!'),
      timePhrase: { morning: 'صباح الخير.', noon: '', maghrib: 'مساء الخير.', night: 'مساء الخير.' },
      connecting: 'لحظة… أجهّز أذنيّ.',
      slow: 'نحتاج وقتًا أطول قليلًا…',
      failed: 'تعذّر بدء الحديث. تأكّد من الإنترنت وجرّب مرة أخرى.',
      retry: 'جرّب مرة أخرى',
      voiceOff: 'الصوت غير متاح الآن، لنكمل بالكتابة.',
      type: 'اكتب للصديق',
      ended: 'انتهى حديثنا. نحكي مرة ثانية؟',
      again: 'ابدأ حديثًا جديدًا',
      level: (n) => `المستوى ${n}`,
      levelAria: (n, pct) => `المستوى ${n}، ${pct} بالمئة`,
      // avatar-integ: the meadow Home (WebUI photo 2)
      salam: (name) => (name ? `السلام عليكم يا ${name}!` : 'السلام عليكم يا صديقي!'),
      salamLead: 'السلام عليكم يا ', // i18n: the greeting split around the name, so the name can sit in its own <bdi> // avatar-integ
      lv: (n) => `م ${n}`,
      streak: (n) => (n === 1 || n === '١' || n === '1' ? 'يوم واحد متتالٍ' : `${n} أيام متتالية`), // qa: n arrives as a formatted digit string
      points: (n) => `+${n} نقطة`,
      questLabel: 'مهمة لك',
      questTitle: 'اكتشف مهامك',
      nav: { home: 'الرئيسية', quests: 'المهام', badges: 'الأوسمة', settings: 'الإعدادات' },
      toast: { points: (n) => `+${n} نقطة`, lost: (n) => `${n} نقطة`, level: (n, name) => (name ? `المستوى ${n}: ${name}!` : `المستوى ${n}!`), quest: (t) => `أنجزت المهمة: ${t}` },
      sound: { on: 'الصوت يعمل', off: 'الصوت متوقف' },
      stageLabel: 'الصديق',
      levels: {
        'New Friend': 'صديق جديد',
        'Kind Companion': 'رفيق لطيف',
        'Helpful Heart': 'قلب مساعد',
        'Brave Heart': 'قلب شجاع',
        'Wise Explorer': 'مستكشف حكيم',
        'Patient Star': 'نجم صبور',
        'Noble Guide': 'دليل نبيل',
        'Radiant Soul': 'روح مشرقة',
      },
    },
  },
  en: {
    dir: 'ltr',
    lang: 'en',
    brand: 'Al-Sadiq Al-Sadouq',
    brandShort: 'Al-Sadiq',
    toggleLabel: 'التبديل إلى العربية',
    login: 'Sign in',
    headline: 'Al-Sadiq, a truthful friend that teaches 38 Islamic values from verified sources',
    sub: 'A voice companion for children aged 6 to 13. And a calm dashboard where parents see weekly summaries, safety alerts and topics to talk about with their child.',
    cta: 'Try Al-Sadiq',
    ctaLoading: 'Getting a room ready…',
    privacy: 'Demo data only: an imaginary family, and no real child data.',
    judgesTitle: 'For judges: three steps',
    steps: [
      { title: 'Press "Try Al-Sadiq"', body: "You step straight into an imaginary child's room, no account, for 45 minutes." },
      { title: 'Talk to Al-Sadiq', body: 'By voice or by typing. See how he answers a child.' },
      { title: 'Press "Parent view"', body: 'See the week summary and alerts for the same child.' },
    ],
    greetings: {
      morning: 'Assalamu alaikum! Good morning, I am Al‑Sadiq.',
      noon: 'Assalamu alaikum! I am Al‑Sadiq.',
      maghrib: 'Assalamu alaikum! Good evening, I am Al‑Sadiq.',
      night: 'Assalamu alaikum! The stars are out. I am Al‑Sadiq.',
    },
    hint: 'Tap Al-Sadiq to start talking',
    nudge: 'Try tapping the lantern!',
    letsTalk: "Let's talk!",
    birdHello: 'Hello, little bulbul!',
    labels: {
      sadiq: 'Talk to Al-Sadiq',
      lantern: 'Light the lantern',
      lanternLit: 'Call the fireflies',
      book: 'Open the book',
      bird: 'Say hi to the bulbul',
      birdAsleep: 'The bulbul is asleep',
    },
    values: [
      { name: 'Honesty', text: 'I tell the truth, even when it is hard.' },
      { name: 'Trust', text: 'I keep what I am given safe and give it back as it was.' },
      { name: 'Mercy', text: 'I am gentle with people and animals.' },
      { name: 'Gratitude', text: 'I say thank you and value what I have.' },
      { name: 'Kindness to parents', text: 'I help my mum and dad and listen to them.' },
      { name: 'Patience', text: 'I wait calmly and do not give up.' },
    ],
    sleepLetter: 'z',
    timeLabel: 'Time of day in the forest',
    times: { now: 'Now', morning: 'Morning', noon: 'Noon', maghrib: 'Sunset', night: 'Night' },
    soundOn: 'Forest sounds: on',
    soundOff: 'Forest sounds: off',
    busyTitle: 'All rooms are busy',
    retryIn: (s) => `We will try again in ${s}s`,
    retry: 'Try now',
    errorTitle: 'We could not start',
    showcaseTitle: 'Preview only',
    showcaseNote: 'Demo login needs the live server. This page is a preview only.',
    showcaseLink: 'Showcase',
    foot: 'Islamic AI Challenge entry',
    demoBadge: 'Demo',
    parentView: 'Parent view',
    childView: 'Child view',
    startOver: 'Start over',
    newDemo: 'Start a new demo',
    ended: 'Your demo time is over',
    working: 'One moment…',
    startedOver: 'Fresh demo ready',
    bannerAria: 'Demo bar',
    bannerHint: 'Demo with imaginary data',
    idle: {
      talk: 'Start talking',
      working: 'One moment…',
      hello: (name) => (name ? `Hi ${name}!` : 'Hi friend!'),
      timePhrase: { morning: 'Good morning.', noon: '', maghrib: 'Good evening.', night: 'Good evening.' },
      connecting: 'One moment… getting my ears ready.',
      slow: 'Taking a little longer…',
      failed: "Couldn't start the talk. Check the internet and try again.",
      retry: 'Try again',
      voiceOff: "Voice is not available right now. Let's carry on by typing.",
      type: 'Type to Al-Sadiq',
      ended: 'Our talk is over. Talk again?',
      again: 'Start a new talk',
      level: (n) => `Level ${n}`,
      levelAria: (n, pct) => `Level ${n}, ${pct} percent`,
      // avatar-integ: the meadow Home (WebUI photo 2)
      salam: (name) => (name ? `Salam, ${name}!` : 'Salam, friend!'),
      salamLead: 'Salam, ',
      lv: (n) => `Lv ${n}`,
      streak: (n) => (n === 1 ? '1 day streak' : `${n} day streak`),
      points: (n) => `+${n} pts`,
      questLabel: 'A quest for you',
      questTitle: 'Find your quests',
      nav: { home: 'Home', quests: 'Quests', badges: 'Badges', settings: 'Settings' },
      toast: { points: (n) => `+${n} points`, lost: (n) => `${n} points`, level: (n, name) => (name ? `Level ${n}: ${name}!` : `Level ${n}!`), quest: (t) => `Quest complete: ${t}` },
      sound: { on: 'Sound on', off: 'Sound off' },
      stageLabel: 'Al-Sadiq',
      levels: {},
    },
  },
};

/** 123 as Arabic-Indic digits for the Arabic UI; unchanged for English. */
export const localDigits = (n, lang) => (
  lang === 'ar' ? String(n).replace(/\d/g, (d) => '٠١٢٣٤٥٦٧٨٩'[d]) : String(n)
);
