# Generated by Django 5.2.10 on 2026-02-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_state', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('excited', 'Excited'), ('neutral', 'Neutral'), ('confused', 'Confused'), ('angry', 'Angry')], max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('child', 'Child'), ('system', 'System'), ('parent', 'Parent')], max_length=10)),
                ('content', models.TextField()),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=10)),
                ('language', models.CharField(default='en', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.session')),
            ],
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['child'], name='conversatio_child_i_812af4_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['started_at'], name='conversatio_started_4a7e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session'], name='conversatio_session_e1151c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='conversatio_created_52b39e_idx'),
        ),
    ]
