# Generated by Django 5.2.10 on 2026-10-04 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0002_session_livekit_room_name_session_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurnAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=1)),
                ("mode", models.CharField(max_length=24)),
                ("served_item_ids", models.JSONField(blank=True, default=list)),
                ("safety", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turn_audits",
                        to="conversation.session",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="conversatio_session_87d912_idx",
                    )
                ],
            },
        ),
    ]
