# Generated by Django 5.2.10 on 2026-02-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honesty_score', models.FloatField(blank=True, null=True)),
                ('insight_summary', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='conversation.session')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='authentication.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='authentication.parentprofile')),
                ('sessions', models.ManyToManyField(blank=True, related_name='weekly_summaries', to='reporting.sessionreport')),
            ],
        ),
        migrations.AddIndex(
            model_name='sessionreport',
            index=models.Index(fields=['created_at'], name='reporting_s_created_db4c85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklysummary',
            unique_together={('child', 'parent', 'week_start')},
        ),
    ]
