# Generated by Django 5.2.10 on 2026-03-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_childsessionmemory_raw_llm_output'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='childsessionmemory',
            new_name='reporting_c_updated_4c0ca9_idx',
            old_name='reporting_c_updated_8a1b2c_idx',
        ),
    ]
