# Generated by Django 5.2.10 on 2026-04-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_rename_reporting_c_updated_8a1b2c_idx_reporting_c_updated_4c0ca9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysummary',
            name='suggested_topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
