# Generated by Django 5.2.10 on 2026-04-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_suggested_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
