# Generated by Django 5.2.10 on 2026-10-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0005_weeklysummary_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionreport",
            name="sources_used",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
