# Generated by Django 5.2.10 on 2026-06-11 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_childprofile_language_preference_en_default'),
        ('conversation', '0002_session_livekit_room_name_session_status'),
        ('gamification', '0002_quest_ai_generated_session_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['category', 'sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='childquestprogress',
            options={'verbose_name_plural': 'Child quest progress'},
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('streak', 'Streak'), ('honesty', 'Honesty'), ('quest', 'Quest'), ('level', 'Level'), ('conversation', 'Conversation'), ('special', 'Special')], default='special', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='requirement_type',
            field=models.CharField(choices=[('streak_days', 'Streak of N days'), ('quests_completed', 'N quests completed'), ('level_reached', 'Level N reached'), ('honesty_sessions', 'N fully honest sessions'), ('sessions_count', 'N sessions held'), ('points_total', 'N total points'), ('manual', 'Manually awarded')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='badge',
            name='requirement_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childquestprogress',
            name='proof_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='childquestprogress',
            name='verified_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('conversation', 'Conversation'), ('real_world', 'Real World'), ('reflection', 'Reflection')], default='real_world', max_length=20),
        ),
        migrations.AddField(
            model_name='quest',
            name='verification_method',
            field=models.CharField(choices=[('self', 'Self-reported'), ('companion', 'Companion-verified'), ('parent', 'Parent-verified')], default='self', max_length=20),
        ),
        migrations.AlterField(
            model_name='childquestprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed')], default='not_started', max_length=25),
        ),
        migrations.CreateModel(
            name='ChildStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='authentication.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PointsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('conversation', 'Conversation'), ('quest', 'Quest'), ('streak', 'Streak'), ('badge', 'Badge'), ('adjustment', 'Adjustment')], default='adjustment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_events', to='authentication.childprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_events', to='conversation.session')),
            ],
            options={
                'indexes': [models.Index(fields=['child', 'created_at'], name='gamificatio_child_i_3ca62d_idx')],
            },
        ),
    ]
