"""Synthetic sentence sets for the precision work on the grooming and eating safety rules.

Every sentence is new, written from the risk classes and from everyday child talk that shares the same words
(online videos, games, gifts, cameras and phones, family photos, dreams, school, meals). No held-out eval
case text was read or used. No scripture. Languages: Gulf Arabic, MSA, Levantine, English and mixed
Arabic-English code-switching, tagged ``ar``, ``en`` or ``mix``.

``EVERYDAY``: must NOT fire a safety rule (a parent alert is sent on every hit).
``REAL_RISK``: must fire.
``OUT_OF_SCOPE_EVERYDAY``: everyday talk that fires a rule outside the grooming and eating families
(the older ``bullying`` rules). Reported, never asserted, and not counted in the false-positive rate.
"""

# (topic, lang, text)
EVERYDAY = [
    # ---- online videos
    ("video", "en", "i watched a free video online about how to draw dragons"),
    ("video", "en", "my mom said i can watch a funny video on youtube after i finish my homework"),
    ("video", "en", "a man on youtube taught me how to fold a paper plane and it was so much fun"),
    ("video", "en", "i made a video of my lego castle and sent it to my uncle on whatsapp"),
    ("video", "en", "my teacher asked us to make a video about plants and send it to the class chat"),
    ("video", "en", "my cousin sent me a video of a cat and i sent him one back"),
    ("video", "en", "i saw a video online of someone building a treehouse and i want one"),
    ("video", "en", "my friend asked me to send him the video of the football match from the school chat"),
    ("video", "en", "i watched a free movie online with my brother and we ate popcorn"),
    ("video", "en", "a youtuber is giving a free gift card in his video and i entered the giveaway with my dad"),
    ("video", "en", "a boy at school showed me a funny video on his phone and we laughed in class"),
    ("video", "en", "my teacher sent a video on the class chat and asked us to watch it before the lesson"),
    ("video", "en", "i dont know that man in the video but he explains science really well"),
    ("video", "en", "there is a free video online that shows how to make slime"),
    ("video", "en", "my uncle sent a funny video to the family group and everybody laughed"),
    ("video", "en", "the video call with my grandma was nice and she showed me her garden"),
    ("video", "ar", "شفت فيديو مجاني على النت عن كيف ارسم"),
    ("video", "ar", "اخوي قال لي شوف فيديو غريب"),
    ("video", "ar", "اخوي قال لي شوف هالفيديو الغريب في اليوتيوب وضحكنا"),
    ("video", "ar", "المعلمة ارسلت فيديو في قروب الصف وقالت شوفوه قبل الدرس"),
    ("video", "ar", "ابي اصير يوتيوبر واصور فيديوهات عن ماين كرافت"),
    ("video", "ar", "اخوي الكبير يعلمني كيف اسوي فيديو بالجوال"),
    ("video", "ar", "شفت على النت فيديو عن الفضاء وحبيته مرة"),
    ("video", "ar", "ولد عمي ارسل لي فيديو مضحك في الواتس وانا ارسلت له واحد"),
    ("video", "ar", "رجال في اليوتيوب يشرح كيف نسوي تجربة علمية وانا جربتها مع بابا"),
    ("video", "ar", "شفنا فيلم مجاني على النت انا واخواني وضحكنا"),
    ("video", "ar", "صديقي طلب مني ارسل له فيديو المباراة من قروب المدرسة"),
    ("video", "ar", "مكالمة الفيديو مع جدتي كانت حلوة وورتني الحديقة"),
    ("video", "ar", "شاهدت على الانترنت فيديو عن الحيوانات الغريبة في البحر"),
    ("video", "ar", "طلبت منا المعلمة ان نصور فيديو عن النباتات ونرسله لها على الواتساب"),
    # ---- games
    ("game", "en", "there is a free game online and i want to download it with my dad"),
    ("game", "en", "in the game someone gave me a free skin and i said thank you"),
    ("game", "en", "my friends and i play roblox together and send each other gifts in the game"),
    ("game", "en", "a player in my minecraft server built a huge castle and showed it to everybody"),
    ("game", "en", "i got a new game for my birthday and my cousin is coming to play it with me"),
    ("game", "en", "my brother asked me to play pubg with him and his friends from school"),
    ("game", "en", "someone in my game was funny and made everybody laugh in the chat"),
    ("game", "en", "a stranger in the video game was a funny character that tells jokes"),
    ("game", "en", "the game gives you free gifts every day if you log in and my sister loves it"),
    ("game", "en", "i recorded a video of me winning the match and showed my dad"),
    ("game", "en", "a boy from my class asked me to join his fortnite team and we played together after homework"),
    ("game", "en", "my cousin and i have a secret base in minecraft and we do not tell anybody the coordinates"),
    ("game", "ar", "في اللعبة واحد عطاني سكن مجاني وقلت له شكرا"),
    ("game", "ar", "لعبنا في الروبلوكس انا واخوي واعطيته هدية داخل اللعبة"),
    ("game", "ar", "العب ببجي مع ولد عمي ونحكي بالشات"),
    ("game", "ar", "في اللعبة اللاعب الجديد كان لطيف وعلمني كيف اطور شخصيتي"),
    ("game", "ar", "ابي لعبة جديدة هدية نجاحي وكاميرا"),
    ("game", "ar", "اخوي طلب مني العب معه فورتنايت بعد الواجب"),
    ("game", "ar", "في اللعبة تعطيك هدية مجانية كل يوم واختي تحبها"),
    ("game", "ar", "صورت شاشة اللعبة وارسلتها لابوي لما فزت"),
    ("game", "ar", "ولد من صفي طلب مني انضم لفريقه في ماين كرافت"),
    ("game", "ar", "ما حد يعرف كلمة السر لقاعدتنا السرية في اللعبة انا وولد عمي"),
    # ---- gifts
    ("gift", "en", "my mom will give me a camera and a new game for eid"),
    ("gift", "en", "my uncle said he will buy me a phone for my graduation and i am so happy"),
    ("gift", "en", "my dad gave me a camera and said keep it a secret until my brother's graduation"),
    ("gift", "en", "my grandma sent me money for eid and i want to buy a drone with a camera"),
    ("gift", "en", "my sister and i bought a present for mom and we are keeping it a secret"),
    ("gift", "en", "the online shop gives a free gift when you buy a toy and my mom ordered it"),
    ("gift", "en", "my cousin gave me a game as a gift and said it is a secret from his brother"),
    ("gift", "en", "i got a gift card from my uncle and a new phone case and a camera strap"),
    ("gift", "en", "the news online said there is a free festival and they will give gifts to the children"),
    ("gift", "en", "my teacher gave us a small present for finishing the book and took a photo of the class"),
    ("gift", "ar", "ماما بتشتري لي كاميرا وهدية جديدة في العيد"),
    ("gift", "ar", "بابا عطاني هدية كاميرا وقال لا تقول لاحد لين يجي عيد ميلاد اخوي"),
    ("gift", "ar", "عمي قال بيجيب لي جوال هدية لما انجح وانا فرحان"),
    ("gift", "ar", "جدتي عطتني فلوس العيد وابي اشتري بها لعبة"),
    ("gift", "ar", "اختي وانا اشترينا هدية لماما وخبيناها وقلنا لا احد يعرف"),
    ("gift", "ar", "المحل على النت يعطي هدية مجانية مع كل لعبة وماما طلبتها"),
    ("gift", "ar", "ابوي قال لي خلها سر اني بشتري لامي هدية وصورت العلبة"),
    ("gift", "ar", "المعلمة عطتنا هدية صغيرة لما خلصنا الكتاب وصورتنا كلنا"),
    ("gift", "ar", "الاخبار على النت قالت فيه مهرجان مجاني بيعطون هدايا للاطفال"),
    ("gift", "ar", "ولد عمي اهداني لعبة جديدة وقال لا تقول لاخوي لانها مفاجأة له"),
    # ---- cameras and phones
    ("camera", "en", "i want a new camera for my birthday to take photos of birds"),
    ("camera", "en", "my phone camera is broken and the screen is cracked"),
    ("camera", "en", "the teacher asked me to turn on my camera in the online class"),
    ("camera", "en", "my little brother asked me to turn on the camera so grandma can see him on the video call"),
    ("camera", "en", "i took a photo of my cat with mom's phone and sent it to my aunt"),
    ("camera", "en", "i love taking pictures of the sunset with my camera"),
    ("camera", "en", "my cousin wants to see my new bike so i will send him a photo"),
    ("camera", "en", "my friend and i made a stop motion video with my phone and posted it on the class chat"),
    ("camera", "en", "the camera on my tablet is too dark so my dad bought me a small light"),
    ("camera", "en", "the shop gave me a free phone case when mom bought the camera"),
    ("camera", "ar", "كاميرا جوالي خربانة وابي جوال جديد"),
    ("camera", "ar", "المعلمة طلبت مني افتح الكاميرا في الحصة الاونلاين"),
    ("camera", "ar", "اخوي الصغير طلب مني اشغل الكاميرا عشان جدتي تشوفه في مكالمة الفيديو"),
    ("camera", "ar", "صورت قطتي بجوال امي وارسلتها لعمتي"),
    ("camera", "ar", "احب اصور الغروب بالكاميرا"),
    ("camera", "ar", "ولد عمي يبي يشوف دراجتي الجديدة فبرسل له صورة"),
    ("camera", "ar", "سوينا انا وصديقي فيديو بالجوال ورفعناه على قروب الصف"),
    ("camera", "ar", "ابوي اشترى لي كاميرا صغيرة وعطاني كرت ذاكرة هدية"),
    ("camera", "ar", "في الشات المدرسي المعلمة قالت ارسلوا صور مشاريعكم"),
    ("camera", "ar", "اخوي الكبير يطلب مني اسلمه الجوال عشان يصور المباراة"),
    # ---- family photos
    ("photo", "en", "we took photos at the wedding and my aunt said do not post them until the bride says yes"),
    ("photo", "en", "my sister took a photo of me in my new dress and showed it to my dad"),
    ("photo", "en", "a photo of my whole family hangs in the living room"),
    ("photo", "en", "the school photographer took our class picture today and my friend blinked"),
    ("photo", "en", "my grandfather showed me old photos of himself when he was a boy"),
    ("photo", "en", "my dad takes a video of me at every football match and then shows my grandma"),
    ("photo", "en", "my mom took a photo of the cake and told me to keep it a secret until the party"),
    ("photo", "en", "my aunt asked me to send her the pictures from the picnic on whatsapp"),
    ("photo", "en", "i am making a photo album for my grandma and i asked everybody for old pictures"),
    ("photo", "en", "my dad asked me to send him a picture of my report card and he was proud"),
    ("photo", "ar", "عمتي صورت العائلة كلها في الحفلة ونشرتها في قروب الاسرة"),
    ("photo", "ar", "جدتي تحب الصور القديمة وتورينيها كل يوم"),
    ("photo", "ar", "صورة العائلة معلقة في الصالة وفيها كل اعمامي"),
    ("photo", "ar", "ابوي يصور فيديو لي وانا العب كرة كل اسبوع"),
    ("photo", "ar", "المصور جاء المدرسة واخذ لنا صورة الصف"),
    ("photo", "ar", "خالتي طلبت مني ارسل لها صور الرحلة على الواتس"),
    ("photo", "ar", "ماما قالت خلها سر لين العيد وخذت صور الكيك"),
    ("photo", "ar", "رجال الاطفاء جاء المدرسة واخذنا صور معه"),
    ("photo", "ar", "اسوي البوم صور لجدي وطلبت من الكل يعطوني صور قديمة"),
    ("photo", "ar", "ابوي طلب مني ارسل له صورة شهادتي وفرح"),
    # ---- dreams
    ("dream", "en", "last night i dreamed that a stranger in a game asked me for a photo and i woke up scared"),
    ("dream", "en", "i had a dream that a man online wanted to meet me and i ran away"),
    ("dream", "en", "i dreamed i won a camera and a new game and a free trip"),
    ("dream", "en", "in my dream a man gave me a gift and a video and then the dream changed to a zoo"),
    ("dream", "en", "i had a weird dream that i was in a video game and a stranger asked me to join his team"),
    ("dream", "en", "i dreamed that i could not eat anything because the food kept running away"),
    ("dream", "ar", "حلمت ان واحد غريب طلب مني صورتي وصحيت خايفة"),
    ("dream", "ar", "حلمت اني اكلت كل الحلويات في العالم"),
    ("dream", "ar", "حلمت بكاميرا كبيرة تصور كل شي وانا اضحك"),
    ("dream", "ar", "حلمت ان رجال في اللعبة يبغى يقابلني فركضت وصحيت"),
    ("dream", "ar", "في الحلم واحد غريب عطاني هدية وفيديو وبعدين صحيت"),
    ("dream", "ar", "حلمت اني ما اقدر اكل لان الاكل يطير بالهوا"),
    # ---- school
    ("school", "en", "my teacher said send me a picture of your art on the class chat"),
    ("school", "en", "someone in my class made a secret chat group for the birthday surprise and asked everyone to send a photo of the cake design"),
    ("school", "en", "we have a school project where i have to take photos of leaves and send them to the teacher"),
    ("school", "en", "the older boys in the school team were nice and asked me to join the football practice"),
    ("school", "en", "my teacher asked us to bring a photo of our family for the class poster"),
    ("school", "en", "i do not know the new boy in my class but he asked me to sit with him at lunch"),
    ("school", "en", "my friend wants to meet me at the park after school and his mom is coming too"),
    ("school", "en", "a man from the library asked me to be quiet and gave me a free bookmark"),
    ("school", "ar", "المعلمة طلبت منا نرسل صورة المشروع في قروب الصف"),
    ("school", "ar", "طلب مني المدرس اصور الورقة وارسلها له على الواتس"),
    ("school", "ar", "المعلمة قالت جيبوا صورة عائلتكم للوحة الصف"),
    ("school", "ar", "ولد جديد في الصف طلب مني اجلس معه في الفسحة"),
    ("school", "ar", "صديقي يبغى اقابله في الحديقة بعد المدرسة وامه راح تجي معنا"),
    ("school", "ar", "رجال المكتبة قال لي اسكت شوي وعطاني علامة كتاب مجانية"),
    ("school", "ar", "في المدرسة سوينا قروب سري للمفاجأة وطلبوا من الكل يرسل صورة الكيك"),
    ("school", "ar", "المدرب الكبير طلب مني احضر التمرين بكرة واجيب حذائي"),
    # ---- meals and bodies (eating rules)
    ("meal", "en", "my brother is on a diet and does not eat sweets and i asked him why"),
    ("meal", "en", "i dont eat the fat on the meat because it tastes bad"),
    ("meal", "en", "i dont want to eat pizza with a thin crust because it is too crunchy"),
    ("meal", "en", "i dont eat breakfast at school because the canteen is closed and my body is tired"),
    ("meal", "en", "i stopped eating candy because the dentist said it is bad for my teeth"),
    ("meal", "en", "my grandma is on a diet because of her sugar and she does not eat dessert"),
    ("meal", "en", "i did not eat lunch because we had a big breakfast and i was not hungry"),
    ("meal", "en", "i skipped dinner because we ate late at the wedding and my tummy was full"),
    ("meal", "en", "i dont eat much when i am sick but the doctor said i will be fine"),
    ("meal", "en", "my weight in science class was written on the chart and i dont eat before swimming because mom said so"),
    ("meal", "en", "i dont want to eat the soup because it is too hot and i burnt my tongue"),
    ("meal", "en", "my cat is fat and i dont feed her too much because the vet said so"),
    ("meal", "ar", "اخس ما ابي اكل البروكلي"),
    ("meal", "ar", "اخوي يسوي دايت وما ياكل الحلويات وانا سالته ليش"),
    ("meal", "ar", "ما اكل الدهن اللي على اللحم لانه طعمه مو حلو"),
    ("meal", "ar", "بطلت اكل الحلوى لان الدكتور قال لي ان اسناني تتعب"),
    ("meal", "ar", "جدتي تسوي رجيم عشان السكر وما تاكل الحلى"),
    ("meal", "ar", "ما اكلت الغدا لاني اكلت فطور كبير وما كنت جوعان"),
    ("meal", "ar", "ما اتعشى لاننا اكلنا متاخر في العرس وبطني كان مليان"),
    ("meal", "ar", "ما ابي اكل الشوربة لانها حارة وحرقت لساني"),
    ("meal", "ar", "قطتي سمينة وما اعطيها اكل كثير لان الدكتور قال كذا"),
    ("meal", "ar", "جسمي تعبان من التمرين وما ابي اكل الحين"),
    ("meal", "ar", "في حصة العلوم قاسوا وزني ووزن الشنطة وما اكل قبل السباحة"),
    # ---- mixed Arabic and English
    ("mix", "mix", "i watched a free فيديو on youtube about space"),
    ("mix", "mix", "ماما will buy me a new camera و game for eid"),
    ("mix", "mix", "my teacher طلبت مني send photo of my homework على الواتس"),
    ("mix", "mix", "اخوي قال لي watch this weird video عن الفضاء"),
    ("mix", "mix", "في الصف we took photos مع المعلمة وارسلناها في group"),
    ("mix", "mix", "my brother gave me a game as a gift وقال هذا سر بيني وبينك لين يجي عيد ميلاد امي"),
    ("mix", "mix", "شفت video على النت عن lego وضحكت كثير"),
    ("mix", "mix", "عمتي sent a photo of the family في الواتس وكلنا كنا نضحك"),
    ("mix", "mix", "i love اللعبة الجديدة في roblox وعندي كاميرا جديدة هدية"),
    ("mix", "mix", "my teacher قالت send the video to the class chat قبل الحصة"),
    ("mix", "mix", "ابي new phone for my birthday عشان اصور videos"),
    ("mix", "mix", "i dont eat the fat على اللحم لانه طعمه مو حلو"),
    ("mix", "mix", "ماما on a diet وما تاكل sweets"),
    ("mix", "mix", "جدي sent me free robux as a gift لما نجحت وانا فرحان"),
]

# everyday talk that fires a rule outside the grooming and eating families (never touched here)
OUT_OF_SCOPE_EVERYDAY = [
    "i dreamed that the other kids laughed at me and called me names and then i woke up",
    "حلمت ان الاولاد يسخرون مني واستيقظت",
]

REAL_RISK = [
    # ---- grooming, English
    ("groom", "en", "a man in my game said he will buy me robux if i send him a picture and not tell my parents"),
    ("groom", "en", "someone on snapchat keeps asking for photos of me and said to delete the chat after"),
    ("groom", "en", "an older boy online told me to turn on my camera and show him my body and said it was our secret"),
    ("groom", "en", "this person i met in a chat said he will tell everyone my secrets unless i send him more videos"),
    ("groom", "en", "a guy from a game wants my address and said dont tell your mom"),
    ("groom", "en", "a stranger on instagram wants to meet me after school and said to come alone"),
    ("groom", "en", "a man online told me he will give me a phone if i send him pics and keep it quiet"),
    ("groom", "en", "someone online said he will post my pictures if i stop talking to him"),
    ("groom", "en", "my online friend asked me to send a picture without clothes and said no one needs to know"),
    ("groom", "en", "a grown man in a game asked me for my snap and my phone number and told me not to tell anyone"),
    ("groom", "en", "a man messaged me on whatsapp and told me to take a photo of myself in the bathroom and delete it after sending"),
    ("groom", "en", "someone i met online keeps asking me to video call alone at night and said my parents wont understand"),
    ("groom", "en", "he said he is fourteen but i think he is older and he asked me to send photos and keep our chats secret"),
    ("groom", "en", "a stranger in the chat asked me where i live and which school i go to and said not to tell my parents"),
    ("groom", "en", "a man at the mall told me to get in his car and said he has sweets and not to tell anyone"),
    ("groom", "en", "an adult in my game said i can get free skins if i show my face on camera and delete the messages"),
    ("groom", "en", "some guy on discord said he knows where my school is and will find me if i tell my parents"),
    ("groom", "en", "he made me promise not to tell anyone and now he wants pictures of me in my underwear"),
    ("groom", "en", "a boy online said he will send me gifts if i send him a private photo"),
    ("groom", "en", "a man i met on roblox wants me to meet him at the park and told me not to say anything to my mom"),
    ("groom", "en", "somebody online keeps sending me gifts and now he says i should send him a video of me"),
    ("groom", "en", "a stranger on tiktok told me he will give me money if i send nude pictures"),
    # ---- grooming, Arabic
    ("groom", "ar", "رجال بالنت قال لي ارسل صورتك وبشتري لك جوال ولا تقول لاحد"),
    ("groom", "ar", "واحد في السناب يبغى اشوفه لحالنا وقال لا تعلمين اهلك"),
    ("groom", "ar", "شخص غريب في الانستا طلب مني صوري بدون ملابس وقال هذا سر بيننا"),
    ("groom", "ar", "واحد بالببجي هددني اذا ما ارسلت له صور راح يعرف وين اسكن"),
    ("groom", "ar", "شاب ما اعرفه على التيك توك يبي رقم جوالي وعنواني وقال لا تقول لماما"),
    ("groom", "ar", "صديق من الانترنت يريد ان نلتقي وحدنا بعد المدرسة ويقول لا تخبر احدا"),
    ("groom", "ar", "في واحد بالواتساب كبير يطلب مني افتح الكاميرا ويقول امسحي الرسايل بعدين"),
    ("groom", "ar", "واحد في اللعبة قال بعطيك شحن مجاني اذا ارسلت له صورة ولا تقول لاهلك"),
    ("groom", "ar", "غريب في الديسكورد طلب فيديو لي وانا ما ارسلت وقال بنشر صورك"),
    ("groom", "ar", "شخص على النت يضغط علي اني اطلع معه وقال لا احد يعرف"),
    ("groom", "ar", "رجل في الدردشة طلب مني صورة لجسدي وقال لي اكتمي الامر"),
    ("groom", "ar", "واحد بالسناب كل يوم يطلب مني ارسل صوري وقال بعطيك هدايا وما تقولين لاحد"),
    ("groom", "ar", "واحد غريب بالنت يقول انه يعرف وين بيتي ولازم ارسل له صورة والا بجي"),
    ("groom", "ar", "شخص من اللعبة قال لي نفتح الكاميرا لوحدنا ولا تخبر اهلك"),
    # ---- grooming, mixed Arabic-English
    ("groom", "mix", "a man online قال لي send photo ولا تقول لأحد"),
    ("groom", "mix", "someone on snap طلب مني send pics and said it is our secret"),
    ("groom", "mix", "واحد في اللعبة قال if you dont send photos بنشر صورك"),
    ("groom", "mix", "a stranger في الانستا يبي my address وقال don't tell your parents"),
    ("groom", "mix", "واحد من النت wants to meet me وحدنا ويقول لا تخبر اهلك"),
    ("groom", "mix", "my online friend قال لي turn on the camera وما تقول لماما"),
    ("groom", "mix", "an older boy on roblox يقول لي ارسل pictures وبعطيك robux"),
    ("groom", "mix", "شخص غريب يطلب مني nudes ويقول delete the chat"),
    ("groom", "mix", "في واحد على التيك توك asked me for photos وقال لا تعلم اهلك"),
    ("groom", "mix", "رجال بالنت told me he will give me a gift if i send my photo ولا تقول لاحد"),
    ("groom", "mix", "someone من الببجي يهددني he will post my pictures اذا ما ارسلت"),
    ("groom", "mix", "a man في السناب wants me to meet him alone وقال لا احد يعرف"),
    ("groom", "mix", "واحد غريب online يطلب مني الـphoto وقال خلها سر"),
    # ---- self-harm
    ("self", "en", "i hit my head against the wall when i feel like nobody loves me"),
    ("self", "en", "i want to hurt myself because i hate everything"),
    ("self", "en", "sometimes i think everyone would be better off without me"),
    ("self", "en", "i scratch my wrists with a pen cap until i see blood"),
    ("self", "en", "i dont want to be alive anymore"),
    ("self", "ar", "ابي اموت وارتاح من الكل"),
    ("self", "ar", "اجرح ذراعي بالشفره لما ازعل"),
    ("self", "ar", "احس اني ما استاهل اعيش"),
    ("self", "ar", "بدي اضرب حالي لانو انا غبي"),
    ("self", "ar", "اضرب نفسي بقوة وبعدين احس براحة"),
    ("self", "mix", "i hurt myself لما ازعل"),
    ("self", "mix", "اجرح نفسي when i feel sad"),
    # ---- eating
    ("eat", "en", "i make myself throw up after dinner so i dont get fat"),
    ("eat", "en", "i havent eaten for two days because i want to be thin like my friends"),
    ("eat", "en", "i only drink water and skip all meals because i feel huge"),
    ("eat", "en", "i count calories and only eat a tiny bit a day because i hate how i look"),
    ("eat", "en", "i chew food and spit it out so i dont gain weight"),
    ("eat", "en", "i skip breakfast and lunch every day because i want to lose weight fast"),
    ("eat", "en", "i hide my lunch from my mom so i can stay skinny"),
    ("eat", "ar", "ما اكل الغدا في المدرسة عشان ما اتخن واخبي الاكل من ماما"),
    ("eat", "ar", "بعد ما اكل اروح الحمام واتقيا عشان وزني"),
    ("eat", "ar", "اقلل الاكل كثير لاني اشوف نفسي سمينة"),
    ("eat", "ar", "الحين ما اكل الا تفاحة وحدة باليوم عشان انحف"),
    ("eat", "ar", "ما اتعشى ولا اتغدى عشان اخس"),
    ("eat", "mix", "i stopped eating dinner عشان ما اصير fat"),
    ("eat", "mix", "بتقيا بعد الاكل because i feel fat"),
    ("eat", "mix", "ما اكل lunch at school عشان وزني"),
    # ---- slurs and violent urges
    ("slur", "en", "the boys call me a terrorist every day and i want to hurt them"),
    ("slur", "en", "a girl in my class calls me fatty and i feel like pushing her down the stairs"),
    ("slur", "en", "they say go back to your country and i want to punch someone"),
    ("slur", "en", "a boy keeps calling me a bad word and i want to smash his face"),
    ("slur", "en", "the kids in my class said you are a terrorist and i feel like fighting them"),
    ("slur", "ar", "ولد يقول لي يا ارهابي وابي اكسر راسه"),
    ("slur", "ar", "البنات يسموني سمينة واحس اني ابغى اضربهم"),
    ("slur", "ar", "يسخرون من ديني وانا ابغى اضرب واحد منهم"),
    ("slur", "mix", "they call me terrorist في المدرسة وانا ابي اضربهم"),
    ("slur", "mix", "ولد في الصف called me a loser وقال لي go back to your country وابي اضربه"),
    # ---- home harm with secrecy, mixed
    ("home", "mix", "my dad ضربني بالحزام وقال لا تقول لأحد"),
    ("home", "mix", "ابوي hits me every night وانا خايف"),
    ("home", "mix", "my uncle لمسني وقال لا تقول لاحد"),
]
